### ISSUE TITLE
google drive, discord webpage error (may be more) (Win 32 build only) #FIXED

### ISSUE THREAD

**Issue by xdeadstokex** [Alex313031/thorium-legacy#62]
**System Details**
 - OS: 7 10
version:( both SS2 and SS3 win 32)
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/bce9ab88-c051-4deb-ade3-d798dd6e8759)

**Problem**
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/a9d8ceb6-9509-43e1-ac06-fa8d05c01be4)
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/38f394b3-93d7-447a-b50e-b6a2d53f9ae5)
the problems still persist...

**Comment by witchkiller9999** [comment]
Same here. I downgraded back to the Jan. 17 M119 release so I can get google drive working again.

**Comment by Dratas** [comment]
same issue here with win 7 32bit os and sse3 32-bit thorium newest version,after sign-in in discord,site gives error more specific in discord.com/app website status_violation.I like that back non-square tabs form in settings.

**Comment by Alex313031** [comment]
@Dratas @witchkiller9999 @xdeadstokex This issue in the 32 bit versions was fixed in a recent commit. Next build will be an updated version of M122, which will have this fix. Stay tuned!

**Comment by Alex313031** [comment]
@xdeadstokex Do you have #force-gdi turned on? Looks like GDI font. If so, It seems the spacing in the copyright is screwed up, it's too much to the left, and also causes Build! to be on another line

**Comment by xdeadstokex** [comment]
@Alex313031 i haven't check it yet (on a military course right now), but it was a fresh .zip extract and run in portable mode, so the setting and flags was not changed at all ( maybe the font is weird because i turned off all window visual effect, which may change the font of thorium)

**Comment by xdeadstokex** [comment]
@Alex313031 tested with the new 122 build SSE2 WIN 32 in win 10 64 bit (fresh zip run in portable mode) (im away from home so win 7 not yet tested)
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/3633770c-2ebf-4eb9-b6b6-d6c44fafc6e1)
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/164dea6f-0a13-476a-be80-03b598cf64cf)
![image](https://github.com/Alex313031/thorium-win7/assets/129391255/17183bab-6eef-4b81-a81c-b289a7312174)

**Comment by witchkiller9999** [comment]
Was about to say the same. I'm on win 8.1, tested with a fresh zip of the new SSE3 32-bit build, and google drive still crashed.

**Comment by Alex313031** [comment]
@witchkiller9999 Is this with the .158 build?

**Comment by witchkiller9999** [comment]
Yes.

**Comment by xdeadstokex** [comment]
@Alex313031 also tested on win 7 today, same result as above

**Comment by Stepman123** [comment]
[telegram.org](https://telegram.org/)
Just like discord.
109 and SSE2 122.0.6261.158

**Comment by witchkiller9999** [comment]
@Alex313031
Good news: I'm happy to report that I got google drive to work in the newest release (M122 v3 SSE3 32-bit zip). I'm on win 8.1.

Bad news: When I upgraded from M119, the newest version said my settings were corrupt so I had to reset it, my extensions all stopped working, the browser profile sign-in refused to stay signed in when restarting, and I lost my browsing history due to my own misclick. So, I decided to just start over from a fresh install, and I spent the last 5 hours getting back to my normal setup.

Luckily, I had everything  (except history & cookies) backed up. Not going to create a new issue over this, since I don't even know how to describe what went wrong. But maybe this can serve as a warning for others trying to upgrade from the M119 release.

**Comment by xdeadstokex** [comment]
@witchkiller9999 normally, some setting will be reset if you update from any version, but ignore it, dont reset anything, that way nothing will be erased (I made the same mistake before but luckily nothing too bad happened), and remember to backup your user data first (just copy it somewhere else before installing newest version)

**Comment by xdeadstokex** [comment]
@Alex313031 i also test the v3 ss2 win 32 m122, discord,drive, etc... work slendidly, everything is back to normal now, so should i close this post ?

**Comment by Alex313031** [comment]
@Stepman123 @Dratas @xdeadstokex @witchkiller9999 This was an issue with 32 bit builds for all Thorium releases, both here and in the regular repo.

It was due to the fact that I cross-compile the Windows builds on Linux. When doing that, `use_v8_context_snapshot` is normally set to "false", but I was overriding it and setting it to true. This causes V8 to have memory overflows on some JavaScript-heavy sites (like the sites you guys were encountering the issue on). It was fixed in M122 in all the repos via a simple config change > https://github.com/Alex313031/thorium-legacy/commit/5582e51df3541864492f6f651c96cb4acb8a3f46 Notice I commented out the use_v8_context_snapshot line in all the 32 bit `args.gn` files, to just let the Chromium build toolchain decide the proper setting depending on whether one is natively compiling on Windows, or cross compiling for Windows on Linux.

**Comment by UCyborg** [comment]
Legacy versions 122.0.6261.168, both SSE2 and SSE3 still crash **everywhere** for me on Google Drive, Win10, Win11, Win XP, doesn't matter, on multiple different computers. Tested with clean profile, no settings were changed, no extensions installed, just opened the browser and went straight to Google Drive.

**Comment by xdeadstokex** [comment]
@UCyborg could you pls check chrome://version/ of your Thorium, as from my side , it work on intel and amd machines (from old to new one), and also I download the zip one, have not tested the installer one yet.
![image](https://github.com/Alex313031/thorium-legacy/assets/129391255/af037025-d37c-4e75-b810-d7861784cbf6)

**Comment by Stepman123** [comment]
> When doing that, `use_v8_context_snapshot` is normally set to "false", but I was overriding it and setting it to true.

Can this be changed in older versions? For example, how to find the signature in HEX and make a patch?

**Comment by xdeadstokex** [comment]
@UCyborg that version is not widely tested, I'm pleased with the 168 versions so I dont tested them bcs they are minor update branch (not for win 7 and above lol), so bugs are possible, 168 one will work with pretty much almost all window versions (maybe Alex forgot to make change to the XP one ? as the win 32 ones are fixed), welp, I guess in the mean time, you could use 168 version as it is stable and up-to-date.

**Comment by AstroSkipper** [comment]
I can confirm that the most recent legacy version with its installation file **Thorium_SSE2_122.0.6261.168_WINXP_x32.zip**, which is a bit mislabelled as it is actually the Thorium version SSE2 122.0.6261.16**9** WINXP 32-bit, was unfortunately **not** fixed in terms of the **Google Drive** bug. Tested in **Windows XP 32-bit** on an **Intel Pentium 4** single-core CPU.

**Comment by witchkiller9999** [comment]
This issue has unfortunately returned in the latest release: Thorium_WIN32_SSE3_122.0.6261.171

Still the same setup as before: win 8.1 32-bit. Probably going to downgrade again until this gets fixed.

**Comment by xdeadstokex** [comment]
@witchkiller9999 Then best advice for ya, if it work, keep using it till it break, that is the way it is for most things, besides, usually there is no real big different in speed or feature between update, but feel free to report bug to Alex (I recommend open a new issue bcs this issue is closed so Alex might not check and knowing these bugs).

**Comment by witchkiller9999** [comment]
Not really familiar with github. I thought the issue could be re-opened?

Yes, I'm aware I could make a separate issue for what I said in the edit, but I already downgraded. If the dev asks for details on what's wrong, I won't be able to answer without going through the time consuming process of updating and slowing down my device again. I'll just have to be content with a side note.

So yes, it seems I'll be using the previous working release until it breaks. Or... you know... it could somehow get fixed in future releases.
